### ISSUE TITLE
MediaStream.stop() being depreciated

### ISSUE THREAD

**Issue by thg1101** [otalk/localmedia#12]
Don't know if you've noticed, but chrome has been issuing this warning of late:

'MediaStream.stop()' is deprecated and will be removed in M47, around November 2015. Please use 'MediaStream.active' instead.

What they seem to mean is to use something along the lines of:
```
this.stopTracks = function(mediaStream) {
    var tracks = mediaStream.getTracks();
    for(var t in tracks) {
        tracks[t].stop();
    }
}
```

just an example. The November deadline is a bit worrisome though.

**Comment by xdumaine** [comment]
This was already fixed. Are you sure you're using the latest version?

**Comment by thg1101** [comment]
Oh dear. Sorry. Looks like I was using an outdated version. Should've checked the code first.
