### ISSUE TITLE
Fix typo "self.localScreens.splce(idx, 1)" for the .splice function usage

### ISSUE THREAD

**Issue by kashifshamaz21** [otalk/localmedia#13]
there's a typo in the latest master branch library code:
```
self.localScreens = self.localScreens.splce(idx, 1)
```

There's a typo for .splce function, it should be .splice.
Corrected code:

```
self.localScreens = self.localScreens.splice(idx, 1);
```

**Comment by fippo** [comment]
fixed and published as 1.1.2 -- thanks!
