### ISSUE TITLE
Changelog outdated

### ISSUE THREAD

**Issue by dezoxel** [otalk/localmedia#27]
I'm updating package from `4.0.1` to the latest version (`4.0.2`) and want to verify changelog for any potential issues, but [changelog](https://github.com/otalk/localmedia/blob/v4.0.2/CHANGELOG.md) is outdated - latest changes are for the `3.0.0`.

I'm pretty sure nothing will be broken, but it would be great to have the change up to date.

**Comment by xdumaine** [comment]
@dezoxel The change in 3.x -> 4.0.0 was removing webrtc-adapter from dependencies and bundle. See the Releases tab for changesets in each version. I'd be more in favor of removing an explicit changelog, since commits/releases show the explicit changes automatically.

**Comment by dezoxel** [comment]
@xdumaine Thanks, sounds reasonable. GitHub nicely covers changelog functionality.
