### ISSUE TITLE
Is this repository abandoned like SimpleWebRTC?

### ISSUE THREAD

**Issue by lawlietmester** [otalk/localmedia#29]
Is this repository abandoned like SimpleWebRTC?

**Comment by xdumaine** [comment]
@lawlietmester not abandoned. I still use this and plan to continue using it in production. It's used as part of the broader otalk group of modules. Let me know if you need any particular help or have any issues. I'm going to close this just so it's not an open issue, but feel free to continue discussion here or open a new issue for something specific.
