### ISSUE TITLE
shim MediaStreamTrack.getSources (and merge getSources branch)

### ISSUE THREAD

**Issue by fippo** [otalk/localmedia#4]
https://github.com/otalk/localmedia/blob/getsources/index.js#L260 actually has a branch that hides MediaStreamTrack.getSources, but it doesn't shim it in Firefox as suggested in https://github.com/GoogleChrome/webrtc/pull/272

Which is a good idea, I don't want the application code (in our case the haircheck) worry about this.
Possibly this should even add enumerated device labels when there is no consent and the label property is empty.

**Comment by kashifshamaz21** [comment]
@fippo This seems to be a fairly good thing to add to this library. Can we merge this into master. I had a look at the changes proposed in the pull request, it looks fine to me.

**Comment by fippo** [comment]
I actually don't think this is the way to go anymore. See https://github.com/webrtc/adapter/pull/23 for the better way to do it

**Comment by kashifshamaz21** [comment]
@fippo Fair enough, the new approach taken at adapter.js looks better. So then do we plan to take that change and add the "getDevices" API into this library?
