### ISSUE TITLE
'util' module not listed in package.json dependencies

### ISSUE THREAD

**Issue by kashifshamaz21** [otalk/localmedia#7]
In the library source, we require the **util** module but this is not listed under the **dependencies** in the lib's package.json file.

**Comment by kashifshamaz21** [comment]
Also, we should try to use the **util** module which can work both in node.js and in browser with AMD loaders like require.js.
This seems to be doing that: https://github.com/simpleviewinc/util-browser

**Comment by tgabi333** [comment]
There is a browser specific shim included in browserify
